package agreementMaker.userInterface;

public class Help {

	public static String getHelpMenuString() {
		String result = "";
		result += "HELP\n\n";
		
		result+="This Help is just a brief introduction to the AgreementMaker. Can be useful to watch the video available on the distribution website.\n\n";
		
		result += "1) Load source and target ontologies.\n\n";
		
		result += "First open source and target ontologies by clicking on File->Open Source/Target Ontology, and selecting filepath and format.\n";
		result += "OAEI-2007 example ontologies contained in the AM distribution are OWL-N3.\n";
		result += "OAEI-2008 example ontologies contained in the AM distribution are OWL-RDF/XML.\n";
		result += "GEOSPATIAL are XML ontologies\n";
		result += "\n";
		
		result += "2) Browse ontologies\n\n";
		
		result += "Click on a concept node to select it. Click everywhere in the canvas to deselect all. In the description panel on the right is possible to visualize additional informations.\n";
		result += "In a OWL ontology following informations are available: localname, label, comment, seeAlso, isDefinedBy, properties, and individuals\n";
		result += "Class and Property hierarchy are displayed in the canvas.\n";
		result += "In a XML ontology: localname = tag id, label = tag label, comment = tag exp, seeAlso = tag seeAlso, and isDefBy = tag isDefBy, no properties or individuals.\n";
		result += "All xml concepts are displayed as a unique class hierarchy.\n";
		result += "Concepts with multiple ancestors will be duplicated and shown more then once, but they will be aligned once.\n";
		result+= "\n";
		
		result += "3)Run matchers to perform matchings.\n\n";
		
		result += "All matchers are available in the matchers selection menu. Click on details button to view a brief description of the selected matcher, not always available.\n";
		result += "To run the selected matcher click on the Match button.Common parameters like threshold and number of relations has to be set before the match operations. Default values are automatically selected.\n";
		result += "Any matcher will perform the similarity between each source concept with each target concept building a similarity matrix.\n";
		result += "Alignments will be selected from the matrix if their similarity is higher then the threshold, and if they satisfy the maximal number or relations for source and target.\n";
		result += "This process is done for classes and matrix if the matcher align both.\n";
		result += "Each matcher will be saved in a new row of the table of the control panel. From there is possible to modify parameters after the execution.Is it also possible to delete matchers.\n";
		result += "Some matchers can run just with common parameters, Some other need more parameters that will be required by the proper panel.\n";
		result += "Some matchers requires other matching result in input, so is not possible to run them without having run other matcher first.\n";
		result += "Matchers that can run first are Base_similarity or Parametric String matcher, while DSI and SSC must run after selecting the output of a previous one.\n";
		result += "\n";
		
		result += "4) Manual mappings.\n\n";
		
		result += "Is it possible to add new mappings or edit mappings generated by any matcher.\n";
		result += "Select source nodes and target nodes that needs to be aligned using left click and optionally shift or ctrl for multiple selections.\n";
		result += "A popup menu will appear which allow the user to create a standard mapping 100% similarity or to create any kind of mapping inserting the required similiraty value.\n";
		result += "Is it also possible to modify the similarity or to delete a previous generated mapping.\n";
		result += "If no matchers are selected in the table, then all manual changes will be applied only to the User Manual Matcher.\n If any other matcher is selected then manual changes will be applied to all of them.\n";
		result += "Is it also possible to create an empty matcher to allow the user to have different set of manual mappings.\n";
		result += "\n";
		
		
		
		
		
		return result;
		
	}
}
