//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 02:34:55 PM CST 
//


package am.batchMode.simpleBatchMode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleBatchModeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simpleBatchModeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ontologies" type="{http://www.example.org/SimpleBatchMode}ontologiesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simpleBatchModeType", namespace = "http://www.example.org/SimpleBatchMode", propOrder = {
    "ontologies"
})
public class SimpleBatchModeType {

    @XmlElement(namespace = "http://www.example.org/SimpleBatchMode", required = true)
    protected OntologiesType ontologies;

    /**
     * Gets the value of the ontologies property.
     * 
     * @return
     *     possible object is
     *     {@link OntologiesType }
     *     
     */
    public OntologiesType getOntologies() {
        return ontologies;
    }

    /**
     * Sets the value of the ontologies property.
     * 
     * @param value
     *     allowed object is
     *     {@link OntologiesType }
     *     
     */
    public void setOntologies(OntologiesType value) {
        this.ontologies = value;
    }

}
