//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 02:34:55 PM CST 
//


package am.batchMode.simpleBatchMode;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the am.batchMode.simpleBatchMode package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SimpleBatchMode_QNAME = new QName("http://www.example.org/SimpleBatchMode", "simpleBatchMode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: am.batchMode.simpleBatchMode
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleBatchModeType }
     * 
     */
    public SimpleBatchModeType createSimpleBatchModeType() {
        return new SimpleBatchModeType();
    }

    /**
     * Create an instance of {@link OntologyType }
     * 
     */
    public OntologyType createOntologyType() {
        return new OntologyType();
    }

    /**
     * Create an instance of {@link OntologiesType }
     * 
     */
    public OntologiesType createOntologiesType() {
        return new OntologiesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleBatchModeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/SimpleBatchMode", name = "simpleBatchMode")
    public JAXBElement<SimpleBatchModeType> createSimpleBatchMode(SimpleBatchModeType value) {
        return new JAXBElement<SimpleBatchModeType>(_SimpleBatchMode_QNAME, SimpleBatchModeType.class, null, value);
    }

}
