//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 02:34:55 PM CST 
//


package am.batchMode.simpleBatchMode;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ontologiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ontologiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="ontology" type="{http://www.example.org/SimpleBatchMode}ontologyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ontologiesType", namespace = "http://www.example.org/SimpleBatchMode", propOrder = {
    "ontology"
})
public class OntologiesType {

    @XmlElement(namespace = "http://www.example.org/SimpleBatchMode", required = true)
    protected List<OntologyType> ontology;

    /**
     * Gets the value of the ontology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ontology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOntology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OntologyType }
     * 
     * 
     */
    public List<OntologyType> getOntology() {
        if (ontology == null) {
            ontology = new ArrayList<OntologyType>();
        }
        return this.ontology;
    }

}
