package am.userInterface.canvas2.popupmenus;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import am.userInterface.canvas2.utility.Canvas2Layout;

public class DeleteMappingMenu extends JPopupMenu {

	private static final long serialVersionUID = 3231794310838624406L;

	public DeleteMappingMenu( Canvas2Layout layout ) {
		super();
		
		// menu layout - Jan 29, 2010 Cosmin
		//  1. Delete Mappings (selected matchers) (item)
		//  2. Delete Individual Mappings   (menu)  TODO
		//     <autogenerated menu>
		//  --------------------
		//  3. Delete All Mappings (item)
		
		JMenuItem miDeleteSelected = new JMenuItem("Delete Mappings (selected matchers)");
			      miDeleteSelected.setActionCommand("DELETE_SELECTED");
			      
		//JMenu     mDeleteIndividual = new JMenu("Delete Individual Mappings");
		
		JMenuItem miDeleteAll = new JMenuItem("Delete All Mappings");
		          miDeleteAll.setActionCommand("DELETE_ALL");
				  		
		add(miDeleteSelected);
		addSeparator();
		add(miDeleteAll);
		
		
		// Listeners
		miDeleteSelected.addActionListener(layout);
		miDeleteAll.addActionListener(layout);
	}
	
	
}
