package am.tools.SGMLParser.GigaWordParser;

/* Generated By:JavaCC: Do not edit this line. GigaWordParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GigaWordParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE_ATTR = 5;
  /** RegularExpression Id. */
  int ID_ATTR = 6;
  /** RegularExpression Id. */
  int GT = 7;
  /** RegularExpression Id. */
  int LT = 8;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int GWENG_TAG = 10;
  /** RegularExpression Id. */
  int GWENG_END_TAG = 11;
  /** RegularExpression Id. */
  int DOC_TAG = 12;
  /** RegularExpression Id. */
  int DOC_END_TAG = 13;
  /** RegularExpression Id. */
  int HEADLINE_TAG = 14;
  /** RegularExpression Id. */
  int HEADLINE_END_TAG = 15;
  /** RegularExpression Id. */
  int DATELINE_TAG = 16;
  /** RegularExpression Id. */
  int DATELINE_END_TAG = 17;
  /** RegularExpression Id. */
  int TEXT_TAG = 18;
  /** RegularExpression Id. */
  int TEXT_END_TAG = 19;
  /** RegularExpression Id. */
  int P_TAG = 20;
  /** RegularExpression Id. */
  int P_END_TAG = 21;
  /** RegularExpression Id. */
  int corruption_TAG = 22;
  /** RegularExpression Id. */
  int corruption_END_TAG = 23;
  /** RegularExpression Id. */
  int CHAR = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"type=\"",
    "\"id=\"",
    "\">\"",
    "\"<\"",
    "\"\\\"\"",
    "\"<GWENG>\"",
    "\"</GWENG>\"",
    "\"DOC\"",
    "\"</DOC>\"",
    "\"<HEADLINE>\"",
    "\"</HEADLINE>\"",
    "\"<DATELINE>\"",
    "\"</DATELINE>\"",
    "\"<TEXT>\"",
    "\"</TEXT>\"",
    "\"<P>\"",
    "\"</P>\"",
    "\"<corruption>\"",
    "\"</corruption>\"",
    "<CHAR>",
  };

}
